// GENERATED by fadymondy.com-v2/packages/sync-feedback.mjs from packages/feedback-sdk/react/feedback-launcher.tsx — do not edit here, edit packages/feedback-sdk.

"use client"

import { useState, type ReactNode } from "react"
import { MessageSquarePlusIcon } from "lucide-react"

import { Button } from "@/components/ui/button"

import { submit, type SubmitFn, type SubmitOptions } from "../core/transport"
import { FEEDBACK_LABELS } from "./labels"
import { ReportDialog, type ReportDialogProps } from "./report-dialog"

export type FeedbackLauncherProps = Omit<ReportDialogProps, "open" | "onOpenChange" | "onSubmit" | "mode" | "initial"> & {
  /** An endpoint (multipart POST) or a host submitter. */
  target: string | SubmitFn
  submitOptions?: SubmitOptions
  /** Called after a successful submit, e.g. to toast. */
  onSubmitted?: (result: unknown) => void
  /** Replaces the default icon + label inside the button. */
  children?: ReactNode
  variant?: "default" | "outline" | "ghost" | "secondary"
  size?: "default" | "sm" | "lg"
  className?: string
}

/**
 * A button that opens the reporter. For a menu item instead, render
 * `ReportDialog` directly and open it from the item.
 */
export function FeedbackLauncher({
  target,
  submitOptions,
  onSubmitted,
  children,
  variant = "outline",
  size = "sm",
  className,
  ...dialog
}: FeedbackLauncherProps) {
  const [open, setOpen] = useState(false)
  const label = dialog.labels?.launcher ?? FEEDBACK_LABELS[dialog.locale ?? "en"].launcher

  return (
    <>
      <Button variant={variant} size={size} className={className} onClick={() => setOpen(true)}>
        {children ?? (
          <>
            <MessageSquarePlusIcon />
            {label}
          </>
        )}
      </Button>
      <ReportDialog
        {...dialog}
        open={open}
        onOpenChange={setOpen}
        onSubmit={async (payload) => onSubmitted?.(await submit(target, payload, submitOptions))}
      />
    </>
  )
}
