// GENERATED by fadymondy.com-v2/packages/sync-feedback.mjs from packages/feedback-sdk/react/labels.ts — do not edit here, edit packages/feedback-sdk.

/**
 * Every string the reporter renders. A host with its own i18n passes its
 * translations as `labels`; a host without one picks `en` or `ar` by `locale`.
 * `reportHint` may use {console} {errors} {network} {failed}.
 */
export type FeedbackLabels = {
  launcher: string
  reportTitle: string
  reportHint: string
  editTitle: string
  editHint: string
  title: string
  titlePlaceholder: string
  type: string
  priority: string
  details: string
  bodyPlaceholder: string
  attach: string
  screenshot: string
  capturing: string
  selectElement: string
  picking: string
  pickHint: string
  image: string
  attachedCapture: string
  removeAttachment: string
  saving: string
  submitReport: string
  submitEdit: string
  failed: string
  screenshotFailed: string
  pickFailed: string
}

export const FEEDBACK_LABELS: Record<"en" | "ar", FeedbackLabels> = {
  en: {
    launcher: "Report a problem",
    reportTitle: "Report",
    reportHint:
      "The page URL is attached automatically, with {console} console entries ({errors} errors) and {network} requests ({failed} failed).",
    editTitle: "Edit issue",
    editHint: "Title and description accept markdown.",
    title: "Title",
    titlePlaceholder: "What happened?",
    type: "Type",
    priority: "Priority",
    details: "Details",
    bodyPlaceholder: "Steps, what you expected, and any details. Markdown supported.",
    attach: "Attach",
    screenshot: "Screenshot",
    capturing: "Capturing…",
    selectElement: "Select element",
    picking: "Pick an element…",
    pickHint: "Click an element to attach it — Escape to cancel",
    image: "Image",
    attachedCapture: "Attached capture",
    removeAttachment: "Remove attachment",
    saving: "Saving…",
    submitReport: "Send report",
    submitEdit: "Save changes",
    failed: "Could not save the issue",
    screenshotFailed: "The screenshot failed",
    pickFailed: "Could not select an element",
  },
  ar: {
    launcher: "الإبلاغ عن مشكلة",
    reportTitle: "إبلاغ",
    reportHint:
      "يُرفق عنوان الصفحة تلقائيًا، مع {console} مدخلًا في الكونسول ({errors} أخطاء) و{network} طلبًا ({failed} فاشلة).",
    editTitle: "تعديل المشكلة",
    editHint: "العنوان والوصف يدعمان الماركداون.",
    title: "العنوان",
    titlePlaceholder: "ما الذي حدث؟",
    type: "النوع",
    priority: "الأولوية",
    details: "التفاصيل",
    bodyPlaceholder: "الخطوات، وما كنت تتوقعه، وأي تفاصيل أخرى. يدعم الماركداون.",
    attach: "إرفاق",
    screenshot: "لقطة شاشة",
    capturing: "جارٍ الالتقاط…",
    selectElement: "اختيار عنصر",
    picking: "اختر عنصرًا…",
    pickHint: "انقر على عنصر لإرفاقه — Escape للإلغاء",
    image: "صورة",
    attachedCapture: "لقطة مرفقة",
    removeAttachment: "إزالة المرفق",
    saving: "جارٍ الحفظ…",
    submitReport: "إرسال البلاغ",
    submitEdit: "حفظ التغييرات",
    failed: "تعذّر حفظ المشكلة",
    screenshotFailed: "فشلت لقطة الشاشة",
    pickFailed: "تعذّر اختيار عنصر",
  },
}

export function fillLabel(template: string, vars: Record<string, string | number>): string {
  let out = template
  for (const [k, v] of Object.entries(vars)) out = out.replaceAll(`{${k}}`, String(v))
  return out
}
