// GENERATED by fadymondy.com-v2/packages/sync-feedback.mjs from packages/feedback-sdk/react/report-dialog.tsx — do not edit here, edit packages/feedback-sdk.

"use client"

import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react"
import { CameraIcon, CrosshairIcon, ImageIcon, SendIcon, XIcon } from "lucide-react"

// Peer contract: the host's shadcn-on-Base-UI kit. See packages/feedback-sdk/README.md.
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"

import { selectorFor } from "../core/anchor"
import { captureElement, captureViewport, HIDE_MARKER } from "../core/capture"
import { pageContext } from "../core/context"
import { consoleSnapshot, diagnosticsCounts, networkSnapshot } from "../core/diagnostics"
import { pickElement } from "../core/picker"
import type { FeedbackPayload } from "../core/transport"
import { FEEDBACK_LABELS, fillLabel, type FeedbackLabels } from "./labels"

/** What the form edits. In edit mode the host seeds it from the stored report. */
export type FeedbackDraft = {
  title?: string | null
  body?: string | null
  issue_type?: string | null
  priority?: string | null
  screenshot?: string | null
  selector?: string | null
}

/**
 * What `onSubmit` receives. In create mode this is the full wire payload —
 * page context plus the console and network recorded since the app mounted.
 * In edit mode it carries only the form fields: the page context was recorded
 * when the issue was first filed, and editing later would record the wrong page.
 */
export type FeedbackSubmission = FeedbackPayload & { priority?: string }

export type BodyEditorProps = {
  id: string
  value: string
  onValueChange: (value: string) => void
  placeholder: string
  rows: number
}

export type ReportDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
  /** Throw to keep the dialog open and show the error. */
  onSubmit: (submission: FeedbackSubmission) => Promise<unknown>
  mode?: "create" | "edit"
  initial?: FeedbackDraft
  locale?: "en" | "ar"
  labels?: Partial<FeedbackLabels>
  types?: readonly string[]
  typeLabels?: Record<string, string>
  /** Omit (or pass []) to hide the priority field. */
  priorities?: readonly string[]
  priorityLabels?: Record<string, string>
  defaultType?: string
  defaultPriority?: string
  /** Replace the plain Textarea, e.g. with a markdown editor. */
  renderBody?: (props: BodyEditorProps) => ReactNode
  /** Host-only fields, rendered last in the form. The host owns their state. */
  extra?: ReactNode
  /** Prefix for input ids, so two reporters on a page do not collide. */
  idPrefix?: string
}

const DEFAULT_TYPES = ["bug", "feature", "question"]

export function ReportDialog({
  open,
  onOpenChange,
  onSubmit,
  mode = "create",
  initial,
  locale = "en",
  labels: overrides,
  types = DEFAULT_TYPES,
  typeLabels,
  priorities = [],
  priorityLabels,
  defaultType = "bug",
  defaultPriority = "medium",
  renderBody,
  extra,
  idPrefix = "feedback",
}: ReportDialogProps) {
  const labels = { ...FEEDBACK_LABELS[locale], ...overrides }
  const editing = mode === "edit"

  const [title, setTitle] = useState("")
  const [body, setBody] = useState("")
  const [issueType, setIssueType] = useState(defaultType)
  const [priority, setPriority] = useState(defaultPriority)
  const [screenshot, setScreenshot] = useState<string | null>(null)
  const [selector, setSelector] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const [busy, setBusy] = useState<"screenshot" | "element" | null>(null)
  // The dialog stays mounted during a capture and hides itself instead of
  // closing: closing it dropped everything typed so far, and reopening fought
  // the enter animation.
  const [hidden, setHidden] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fileInput = useRef<HTMLInputElement>(null)
  // Read once per open: the counts should describe what will be attached, not
  // tick upward while the form is being filled in.
  const [diagnostics, setDiagnostics] = useState(() => diagnosticsCounts())

  // Reset whenever the dialog opens, so a cancelled edit does not leak into
  // the next one.
  useEffect(() => {
    if (!open) return
    setTitle(initial?.title ?? "")
    setBody(initial?.body ?? "")
    setIssueType(initial?.issue_type ?? defaultType)
    setPriority(initial?.priority ?? defaultPriority)
    setScreenshot(initial?.screenshot ?? null)
    setSelector(initial?.selector ?? null)
    setDiagnostics(diagnosticsCounts())
    setError(null)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, initial])

  const id = (name: string) => `${idPrefix}-${name}`
  const showPriority = priorities.length > 0

  async function submit(e: FormEvent) {
    e.preventDefault()
    if (!title.trim()) return
    setSaving(true)
    setError(null)
    try {
      const fields: FeedbackSubmission = {
        title: title.trim(),
        body: body.trim() || undefined,
        issue_type: issueType,
        priority: showPriority ? priority : undefined,
        screenshot: screenshot ?? undefined,
        selector: selector ?? undefined,
      }
      await onSubmit(
        editing
          ? fields
          : {
              ...fields,
              ...pageContext(),
              // Recorded continuously since the app mounted, so this covers what
              // happened BEFORE the dialog was opened.
              console_log: consoleSnapshot() || undefined,
              network_log: networkSnapshot() || undefined,
            },
      )
      onOpenChange(false)
    } catch (err) {
      setError(err instanceof Error ? err.message : labels.failed)
    } finally {
      setSaving(false)
    }
  }

  async function grabScreenshot() {
    setBusy("screenshot")
    setError(null)
    setHidden(true)
    // One frame, so the dialog is actually off-screen before the rasteriser
    // walks the DOM.
    await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)))
    try {
      setScreenshot(await captureViewport())
    } catch (err) {
      setError(err instanceof Error ? err.message : labels.screenshotFailed)
    } finally {
      setHidden(false)
      setBusy(null)
    }
  }

  async function grabElement() {
    setBusy("element")
    setError(null)
    setHidden(true)
    await new Promise((resolve) => requestAnimationFrame(resolve))
    try {
      const picked = await pickElement({ hint: labels.pickHint })
      if (picked) {
        setSelector(selectorFor(picked.anchor))
        const shot = await captureElement(picked.element)
        if (shot) setScreenshot(shot)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : labels.pickFailed)
    } finally {
      setHidden(false)
      setBusy(null)
    }
  }

  function readFile(file: File) {
    const reader = new FileReader()
    reader.onload = () => setScreenshot(String(reader.result))
    reader.readAsDataURL(file)
  }

  const bodyProps: BodyEditorProps = {
    id: id("body"),
    value: body,
    onValueChange: setBody,
    rows: 7,
    placeholder: labels.bodyPlaceholder,
  }

  return (
    <Dialog
      open={open}
      onOpenChange={onOpenChange}
      // A modal dialog renders a backdrop over the whole page and takes the
      // page out of the pointer-event tree, so document.elementFromPoint
      // answered with one full-viewport node and the picker could only ever
      // select "the page". Going non-modal for the duration is what makes
      // picking possible at all.
      modal={!hidden}
    >
      <DialogContent
        {...{ [HIDE_MARKER]: hidden ? "" : undefined }}
        className={hidden ? "sm:max-w-xl pointer-events-none opacity-0" : "sm:max-w-xl"}
      >
        <form onSubmit={submit} className="flex flex-col gap-4">
          <DialogHeader>
            <DialogTitle>{editing ? labels.editTitle : labels.reportTitle}</DialogTitle>
            <DialogDescription>
              {editing ? labels.editHint : fillLabel(labels.reportHint, diagnostics)}
            </DialogDescription>
          </DialogHeader>

          <FieldGroup>
            <Field>
              <FieldLabel htmlFor={id("title")}>{labels.title}</FieldLabel>
              <Input
                id={id("title")}
                dir="auto"
                value={title}
                placeholder={labels.titlePlaceholder}
                onChange={(e) => setTitle(e.target.value)}
                required
              />
            </Field>

            <div className={showPriority ? "grid gap-4 sm:grid-cols-2" : "grid gap-4"}>
              <Field>
                <FieldLabel htmlFor={id("type")}>{labels.type}</FieldLabel>
                <Select value={issueType} onValueChange={(v) => setIssueType(v ?? defaultType)}>
                  <SelectTrigger id={id("type")} className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {types.map((t) => (
                      <SelectItem key={t} value={t}>
                        {typeLabels?.[t] ?? t}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </Field>

              {showPriority ? (
                <Field>
                  <FieldLabel htmlFor={id("priority")}>{labels.priority}</FieldLabel>
                  <Select
                    value={priority}
                    onValueChange={(v) => setPriority(v ?? defaultPriority)}
                  >
                    <SelectTrigger id={id("priority")} className="w-full">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {priorities.map((p) => (
                        <SelectItem key={p} value={p}>
                          {priorityLabels?.[p] ?? p}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </Field>
              ) : null}
            </div>

            <Field>
              <FieldLabel htmlFor={id("body")}>{labels.details}</FieldLabel>
              {renderBody ? (
                renderBody(bodyProps)
              ) : (
                <Textarea
                  id={bodyProps.id}
                  dir="auto"
                  value={body}
                  rows={bodyProps.rows}
                  placeholder={bodyProps.placeholder}
                  onChange={(e) => setBody(e.target.value)}
                />
              )}
            </Field>

            {!editing ? (
              <Field>
                <FieldLabel>{labels.attach}</FieldLabel>
                <div className="flex flex-wrap gap-2">
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    className="gap-2"
                    disabled={busy !== null}
                    onClick={grabScreenshot}
                  >
                    <CameraIcon />
                    {busy === "screenshot" ? labels.capturing : labels.screenshot}
                  </Button>

                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    className="gap-2"
                    disabled={busy !== null}
                    onClick={grabElement}
                  >
                    <CrosshairIcon />
                    {busy === "element" ? labels.picking : labels.selectElement}
                  </Button>

                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    className="gap-2"
                    disabled={busy !== null}
                    onClick={() => fileInput.current?.click()}
                  >
                    <ImageIcon />
                    {labels.image}
                  </Button>

                  <input
                    ref={fileInput}
                    type="file"
                    accept="image/*"
                    hidden
                    onChange={(e) => {
                      const file = e.target.files?.[0]
                      if (file) readFile(file)
                      e.target.value = ""
                    }}
                  />
                </div>
              </Field>
            ) : null}

            {selector ? (
              <p className="flex items-center gap-2 font-mono text-xs text-muted-foreground">
                <CrosshairIcon className="size-3.5" />
                <span dir="ltr" className="truncate">
                  {selector}
                </span>
              </p>
            ) : null}

            {screenshot ? (
              <div className="relative overflow-hidden rounded-lg border border-border">
                {/* A data URL, so an image optimiser would add nothing. */}
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={screenshot}
                  alt={labels.attachedCapture}
                  className="max-h-48 w-full bg-muted/30 object-contain"
                />
                <Button
                  type="button"
                  size="icon-sm"
                  variant="outline"
                  aria-label={labels.removeAttachment}
                  className="absolute top-2 end-2"
                  onClick={() => {
                    setScreenshot(null)
                    setSelector(null)
                  }}
                >
                  <XIcon />
                </Button>
              </div>
            ) : null}

            {extra}
          </FieldGroup>

          {error ? (
            <p role="alert" className="text-sm text-destructive">
              {error}
            </p>
          ) : null}

          <DialogFooter>
            <Button type="submit" className="gap-2" disabled={saving || !title.trim()}>
              <SendIcon />
              {saving ? labels.saving : editing ? labels.submitEdit : labels.submitReport}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
