// GENERATED by fadymondy.com-v2/packages/sync-grid.mjs from web/lib/brand/marks.ts — do not edit here.

// Cube-lattice mark system. Every mark is a set of cubes on a square grid
// where a cube may only sit on a cell where (col + row) is odd — this is why
// cubes touch only at corners, never along an edge. Source of truth:
// design_handoff_fady_mondy_brand/README.md.

export type Cell = readonly [col: number, row: number];

export interface MarkSpec {
  name: string;
  cells: readonly Cell[];
  /** Cells rendered in the accent colour instead of the body colour. */
  accentCells: readonly Cell[];
  body: string;
  accent: string;
  /** Body colour to use when rendered on a dark ground, if different. */
  bodyOnDark?: string;
}

export const FADY_MONDY_MARK: MarkSpec = {
  name: "Fady Mondy",
  cells: [
    [1, 0],
    [3, 0],
    [0, 1],
    [2, 1],
    [1, 2],
    [3, 2],
    [0, 3],
    [2, 3],
  ],
  accentCells: [[3, 0]],
  body: "#0E1A3C",
  bodyOnDark: "#F0EBE1",
  accent: "#C9A227",
};

export const PRODUCT_MARKS: Record<string, MarkSpec> = {
  tomatophp: {
    name: "TomatoPHP",
    cells: [
      [3, 0],
      [2, 1],
      [4, 1],
      [3, 2],
      [5, 2],
      [2, 3],
      [4, 3],
      [3, 4],
    ],
    accentCells: [[3, 0]],
    body: "#D64524",
    accent: "#4E9A3E",
  },
  togo: {
    name: "ToGO",
    cells: [
      [0, 1],
      [1, 0],
      [1, 2],
      [2, 1],
      [2, 3],
      [3, 2],
    ],
    accentCells: [
      [2, 1],
      [2, 3],
      [3, 2],
    ],
    body: "#0E1A3C",
    bodyOnDark: "#F0EBE1",
    accent: "#1F8A99",
  },
  laravilt: {
    name: "Laravilt",
    cells: [
      [0, 1],
      [1, 2],
      [0, 3],
      [2, 1],
      [2, 3],
      [3, 2],
      [4, 1],
    ],
    accentCells: [
      [2, 1],
      [2, 3],
      [3, 2],
      [4, 1],
    ],
    body: "#FF2D20",
    accent: "#9553E9",
  },
  "3x1": {
    name: "3x1.io",
    cells: [
      [3, 0],
      [2, 1],
      [4, 1],
      [3, 2],
      [2, 3],
      [4, 3],
      [3, 4],
    ],
    accentCells: [[3, 0]],
    body: "#1FCF4D",
    accent: "#0E7A33",
  },
  "mark-it-down": {
    name: "Mark It Down",
    cells: [
      [1, 0],
      [3, 0],
      [5, 0],
      [2, 1],
      [4, 1],
      [3, 2],
    ],
    accentCells: [[3, 0]],
    body: "#3D5A8C",
    bodyOnDark: "#7E93C4",
    accent: "#C9A227",
  },
  "health-debug": {
    name: "Health Debug",
    cells: [
      [1, 0],
      [3, 0],
      [0, 1],
      [2, 1],
      [4, 1],
      [1, 2],
      [3, 2],
      [2, 3],
    ],
    accentCells: [[3, 0]],
    body: "#B0243F",
    bodyOnDark: "#D9455F",
    accent: "#C9A227",
  },
  circlexo: {
    name: "CircleXO",
    cells: [
      [3, 0],
      [2, 1],
      [4, 1],
      [1, 2],
      [5, 2],
      [2, 3],
      [4, 3],
      [3, 4],
    ],
    accentCells: [[3, 0]],
    body: "#6FA8D6",
    accent: "#C9A227",
  },
  // CaBrain — "the vault": a dome of six cubes over a solid nucleus, standing on two. The only
  // mark in the family whose centre is filled. From CaBrain Brand.dc.html, shifted one column
  // so every cell has odd (col + row); rendering normalises to the bounding box.
  cabrain: {
    name: "CaBrain",
    cells: [
      [3, 0],
      [2, 1],
      [4, 1],
      [1, 2],
      [3, 2],
      [5, 2],
      [2, 3],
      [4, 3],
    ],
    accentCells: [[3, 0]],
    body: "#6D4DE6",
    bodyOnDark: "#F0EBE1",
    accent: "#C9A227",
  },
  "orchestra-mcp": {
    name: "Orchestra MCP",
    cells: [
      [3, 2],
      [4, 3],
      [5, 2],
      [6, 1],
    ],
    accentCells: [[6, 1]],
    body: "#D97757",
    accent: "#8C3B1F",
  },
};
