// GENERATED by fadymondy.com-v2/packages/sync-feedback.mjs from packages/feedback-sdk/core/anchor.ts — do not edit here, edit packages/feedback-sdk.

/**
 * A durable anchor to an element, ported from the builder SDK's `anchor.ts`.
 *
 * A single CSS path is built from tag names and nth-of-type indices, so after a
 * list reorder it silently resolves to a *different* element. Several
 * independent signals are captured instead and scored at resolve time, because
 * confidently pointing at the wrong component is worse than admitting the pin
 * is stale.
 */
export type PinAnchor = {
  tag: string
  hint: string
  css: string
  testid?: string
  domId?: string
  role?: string
  name?: string
  /** Fractions of the viewport, so a pin means the same on another monitor. */
  rect: { x: number; y: number; w: number; h: number }
  scrollY: number
  href: string
}

export function captureAnchor(el: Element): PinAnchor {
  const rect = el.getBoundingClientRect()
  const vw = window.innerWidth || 1
  const vh = window.innerHeight || 1

  const anchor: PinAnchor = {
    tag: el.tagName.toLowerCase(),
    hint: textOf(el),
    css: cssPath(el),
    rect: { x: rect.left / vw, y: rect.top / vh, w: rect.width / vw, h: rect.height / vh },
    scrollY: window.scrollY,
    href: location.href.slice(0, 2048),
  }

  const testid = el.getAttribute("data-testid") ?? el.getAttribute("data-slot")
  if (testid) anchor.testid = testid
  if (el.id && !looksGenerated(el.id)) anchor.domId = el.id

  const role = el.getAttribute("role") ?? implicitRole(el)
  if (role) anchor.role = role
  const name = accessibleName(el)
  if (name) anchor.name = name

  return anchor
}

/** The single selector stored on the report, for a developer to paste. */
export function selectorFor(anchor: PinAnchor): string {
  if (anchor.testid) return `[data-testid="${anchor.testid}"], [data-slot="${anchor.testid}"]`
  if (anchor.domId) return `#${anchor.domId}`
  return anchor.css
}

function cssPath(el: Element): string {
  // Deliberately avoids class names: utility-CSS churn would invalidate every
  // stored pin on the next restyle.
  const parts: string[] = []
  let cur: Element | null = el

  for (let depth = 0; cur && depth < 6 && cur !== document.body; depth++) {
    if (cur.id && !looksGenerated(cur.id)) {
      parts.unshift(`#${cssEscape(cur.id)}`)
      break
    }
    const tag = cur.tagName.toLowerCase()
    const parent: Element | null = cur.parentElement
    if (!parent) {
      parts.unshift(tag)
      break
    }
    const node: Element = cur
    const sameTag = Array.from(parent.children).filter((c) => c.tagName === node.tagName)
    parts.unshift(sameTag.length > 1 ? `${tag}:nth-of-type(${sameTag.indexOf(node) + 1})` : tag)
    cur = parent
  }

  return parts.join(" > ").slice(0, 512)
}

/** React, Emotion and friends emit ids like `:r3:` or `mui-4821`. */
function looksGenerated(id: string): boolean {
  return /^[:#]|^(mui|radix|headlessui|react|ember|base-ui)[-:]?\d|\d{4,}$/i.test(id)
}

function textOf(el: Element): string {
  return (el.textContent ?? "").replace(/\s+/g, " ").trim().slice(0, 120)
}

function accessibleName(el: Element): string {
  const label =
    el.getAttribute("aria-label") ??
    el.getAttribute("title") ??
    (el as HTMLInputElement).placeholder ??
    ""
  return (label || textOf(el)).slice(0, 80)
}

function implicitRole(el: Element): string {
  const tag = el.tagName.toLowerCase()
  if (tag === "button") return "button"
  if (tag === "a" && el.hasAttribute("href")) return "link"
  if (tag === "input") return (el as HTMLInputElement).type === "checkbox" ? "checkbox" : "textbox"
  if (tag === "textarea") return "textbox"
  if (tag === "select") return "combobox"
  if (/^h[1-6]$/.test(tag)) return "heading"
  return ""
}

function cssEscape(s: string): string {
  return (window.CSS?.escape ?? ((x: string) => x.replace(/["\\\]]/g, "\\$&")))(s)
}
