// GENERATED by fadymondy.com-v2/packages/sync-feedback.mjs from packages/feedback-sdk/core/capture.ts — do not edit here, edit packages/feedback-sdk.

import { toBlob } from "html-to-image"

/**
 * Screenshots for the issue reporter, ported from the builder SDK's `capture.ts`.
 *
 * Screenshots rasterise the DOM with html-to-image rather than going through
 * `getDisplayMedia`: a permission prompt per capture is a hard stop for most
 * people, and the picked-element case needs a crop the display stream cannot
 * give reliably (browser chrome height varies, and the shared surface may not
 * even be this tab).
 */

/** Anything carrying this is excluded from a screenshot. */
export const HIDE_MARKER = "data-capture-hide"

/** Elements the reporter itself owns. Never pinnable, never captured. */
export const OWN_MARKER = "data-reporter"

/** A 1x1 transparent PNG stands in for whatever could not be fetched. */
const PLACEHOLDER =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=="

export function isOurs(el: Element | null): boolean {
  return Boolean(
    el?.closest?.(`[${OWN_MARKER}], [data-slot="dialog-content"], [data-slot="sheet-content"]`),
  )
}

/** 10 MB, the same ceiling the SDK uses for an image attachment. */
export const IMAGE_LIMIT = 10 * 1024 * 1024

async function rasterise(node: HTMLElement, timeoutMs = 20000): Promise<Blob> {
  const blob = await Promise.race([
    toBlob(node, {
      // A 3x retina capture of a full page routinely exceeds 20 MB and takes
      // long enough that people assume it hung.
      pixelRatio: Math.min(window.devicePixelRatio || 1, 1.5),
      backgroundColor: getComputedStyle(document.body).backgroundColor || "#ffffff",
      // cacheBust turns a cached same-origin hit into a fresh cross-origin
      // request, and one third-party image answering without CORS headers
      // would reject the entire screenshot.
      cacheBust: false,
      // The output is a PNG, so fonts are already rasterised by the time it is
      // encoded. Inlining the @font-face files only matters for SVG output and
      // costs a network round trip per face — it dominated the capture time.
      skipFonts: true,
      imagePlaceholder: PLACEHOLDER,
      filter: (n) => {
        const el = n as Element
        if (!el?.hasAttribute) return true
        if (el.hasAttribute(OWN_MARKER) || el.hasAttribute(HIDE_MARKER)) return false
        // The dim backdrop belongs to the dialog doing the capturing, and the
        // Next.js dev overlay is not part of the page under test.
        const slot = el.getAttribute("data-slot") ?? ""
        if (slot.endsWith("-overlay")) return false
        if (el.tagName === "NEXTJS-PORTAL") return false
        return true
      },
    }),
    new Promise<null>((_, reject) =>
      setTimeout(() => reject(new Error("The screenshot timed out")), timeoutMs),
    ),
  ])

  if (!blob) throw new Error("The screenshot produced no image")
  if (blob.size > IMAGE_LIMIT) {
    throw new Error(
      `The screenshot is ${(blob.size / 1024 / 1024).toFixed(1)} MB, over the 10 MB limit`,
    )
  }
  return blob
}

export function toDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(String(reader.result))
    reader.onerror = () => reject(new Error("Could not read the capture"))
    reader.readAsDataURL(blob)
  })
}

/** Rasterise the whole page. Resolves to a PNG data URL. */
export async function captureViewport(): Promise<string> {
  return toDataUrl(await rasterise(document.body))
}

/** Rasterise one element. Resolves to a PNG data URL, or null for a zero-size element. */
export async function captureElement(element: Element): Promise<string | null> {
  const rect = element.getBoundingClientRect()
  if (rect.width === 0 || rect.height === 0) return null
  return toDataUrl(await rasterise(element as HTMLElement))
}
