// GENERATED by fadymondy.com-v2/packages/sync-feedback.mjs from packages/feedback-sdk/core/diagnostics.ts — do not edit here, edit packages/feedback-sdk.

/**
 * Console and network recorder for issue reports.
 *
 * A bug report that says "it broke" is worth far less than the same report
 * with the failing request and the error that followed it. The browser cannot
 * hand either of those over after the fact, so both are recorded continuously
 * into a bounded ring buffer from the moment the app mounts.
 *
 * Everything here is best-effort and must never change what the page does:
 * the console patches forward to the originals, and the fetch/XHR patches
 * record and then get out of the way, including on failure.
 */

const MAX_ENTRIES = 100
/** A single console argument, truncated. Stack traces get more room. */
const MAX_ARG = 400

export type ConsoleEntry = {
  level: "log" | "info" | "warn" | "error" | "debug"
  message: string
  at: string
}

export type NetworkEntry = {
  method: string
  url: string
  status: number | null
  ms: number
  at: string
  /** Set when the request never produced a response at all. */
  error?: string
}

const consoleLog: ConsoleEntry[] = []
const networkLog: NetworkEntry[] = []

let installed = false

function push<T>(buffer: T[], entry: T) {
  buffer.push(entry)
  if (buffer.length > MAX_ENTRIES) buffer.shift()
}

function format(value: unknown): string {
  if (typeof value === "string") return value.slice(0, MAX_ARG)
  if (value instanceof Error)
    return `${value.name}: ${value.message}\n${value.stack ?? ""}`.slice(0, MAX_ARG * 2)
  try {
    return JSON.stringify(value)?.slice(0, MAX_ARG) ?? String(value)
  } catch {
    // Circular structures, DOM nodes, proxies.
    return String(value).slice(0, MAX_ARG)
  }
}

/** Same-origin URL as a path, so the log reads as routes rather than origins. */
function shorten(url: string): string {
  try {
    const u = new URL(url, location.href)
    return u.origin === location.origin ? u.pathname + u.search : u.href
  } catch {
    return String(url).slice(0, 300)
  }
}

/** Install once, as early as possible (a root provider's first effect). Safe to call repeatedly. */
export function installDiagnostics() {
  if (installed || typeof window === "undefined") return
  installed = true

  for (const level of ["log", "info", "warn", "error", "debug"] as const) {
    const original = console[level].bind(console)
    console[level] = (...args: unknown[]) => {
      push(consoleLog, {
        level,
        message: args.map(format).join(" "),
        at: new Date().toISOString(),
      })
      original(...args)
    }
  }

  // Errors that never reach console.error — uncaught throws and rejected
  // promises with no handler — are the ones that matter most.
  window.addEventListener("error", (e) => {
    push(consoleLog, {
      level: "error",
      message: `Uncaught ${format(e.error ?? e.message)}${e.filename ? ` (${shorten(e.filename)}:${e.lineno})` : ""}`,
      at: new Date().toISOString(),
    })
  })

  window.addEventListener("unhandledrejection", (e) => {
    push(consoleLog, {
      level: "error",
      message: `Unhandled rejection: ${format(e.reason)}`,
      at: new Date().toISOString(),
    })
  })

  const originalFetch = window.fetch.bind(window)
  window.fetch = async (input, init) => {
    const started = performance.now()
    const method = (init?.method ?? (input instanceof Request ? input.method : "GET")).toUpperCase()
    const url = typeof input === "string" ? input : input instanceof URL ? input.href : input.url

    try {
      const res = await originalFetch(input as RequestInfo, init)
      push(networkLog, {
        method,
        url: shorten(url),
        status: res.status,
        ms: Math.round(performance.now() - started),
        at: new Date().toISOString(),
      })
      return res
    } catch (err) {
      push(networkLog, {
        method,
        url: shorten(url),
        status: null,
        ms: Math.round(performance.now() - started),
        at: new Date().toISOString(),
        error: err instanceof Error ? err.message : String(err),
      })
      // Rethrow untouched: recording must not change how callers see failures.
      throw err
    }
  }

  const open = XMLHttpRequest.prototype.open
  const send = XMLHttpRequest.prototype.send
  type Tracked = XMLHttpRequest & { __method?: string; __url?: string; __started?: number }

  // The overloads differ in arity, so the wrappers forward arguments verbatim
  // rather than trying to restate either signature.
  XMLHttpRequest.prototype.open = function (this: Tracked, ...args: unknown[]) {
    this.__method = String(args[0]).toUpperCase()
    this.__url = String(args[1])
    return (open as (...a: unknown[]) => void).apply(this, args)
  } as typeof XMLHttpRequest.prototype.open

  XMLHttpRequest.prototype.send = function (this: Tracked, ...args: unknown[]) {
    this.__started = performance.now()
    this.addEventListener("loadend", () => {
      push(networkLog, {
        method: this.__method ?? "GET",
        url: shorten(this.__url ?? ""),
        status: this.status || null,
        ms: Math.round(performance.now() - (this.__started ?? performance.now())),
        at: new Date().toISOString(),
        error: this.status ? undefined : "no response",
      })
    })
    return (send as (...a: unknown[]) => void).apply(this, args)
  } as typeof XMLHttpRequest.prototype.send
}

/** The recorded console, newest last, as text for the report field. */
export function consoleSnapshot(limit = 50): string {
  return consoleLog
    .slice(-limit)
    .map((e) => `[${e.at}] ${e.level.toUpperCase()} ${e.message}`)
    .join("\n")
}

/** The recorded network activity, newest last, as text for the report field. */
export function networkSnapshot(limit = 50): string {
  return networkLog
    .slice(-limit)
    .map(
      (e) =>
        `[${e.at}] ${e.method} ${e.url} → ${e.error ? `FAILED (${e.error})` : e.status} ${e.ms}ms`,
    )
    .join("\n")
}

export type DiagnosticsCounts = { console: number; errors: number; network: number; failed: number }

export function diagnosticsCounts(): DiagnosticsCounts {
  return {
    console: consoleLog.length,
    errors: consoleLog.filter((e) => e.level === "error").length,
    network: networkLog.length,
    failed: networkLog.filter((e) => e.error || (e.status ?? 0) >= 400).length,
  }
}
