// GENERATED by fadymondy.com-v2/packages/sync-feedback.mjs from packages/feedback-sdk/core/picker.ts — do not edit here, edit packages/feedback-sdk.

import { captureAnchor, type PinAnchor } from "./anchor"
import { isOurs, OWN_MARKER } from "./capture"

export type PickOptions = {
  /** The banner shown while picking. */
  hint?: string
}

export const DEFAULT_PICK_HINT = "Click an element to attach it — Escape to cancel"

/**
 * Element picker, ported from the builder SDK's `picker.ts`. Hover highlights,
 * click pins, Escape cancels.
 *
 * Every listener is on the capture phase so the host page's own handlers never
 * see these events — otherwise clicking to pin would also navigate.
 *
 * A MODAL dialog that is open while this runs defeats it: see `ReportDialog`,
 * which goes non-modal for the duration of a pick.
 */
export function pickElement(
  options: PickOptions = {},
): Promise<{ element: Element; anchor: PinAnchor } | null> {
  return new Promise((resolve) => {
    const overlay = document.createElement("div")
    overlay.setAttribute(OWN_MARKER, "")
    overlay.style.cssText = [
      "position:fixed",
      "z-index:2147483647",
      "pointer-events:none",
      "border:2px solid var(--brand-accent,#4B00B6)",
      "background:color-mix(in oklab, var(--brand-accent,#4B00B6) 12%, transparent)",
      "transition:top 60ms linear,left 60ms linear,width 60ms linear,height 60ms linear",
      "display:none",
    ].join(";")

    const hint = document.createElement("div")
    hint.setAttribute(OWN_MARKER, "")
    hint.textContent = options.hint ?? DEFAULT_PICK_HINT
    hint.style.cssText = [
      "position:fixed",
      "z-index:2147483647",
      "inset-inline:0",
      "bottom:1rem",
      "margin-inline:auto",
      "width:max-content",
      "max-width:90vw",
      "padding:0.5rem 0.875rem",
      "border-radius:0.75rem",
      "font:500 13px/1.4 system-ui,sans-serif",
      "color:#fff",
      "background:rgba(0,0,0,0.8)",
      "pointer-events:none",
    ].join(";")

    document.body.append(overlay, hint)
    const previousCursor = document.body.style.cursor
    document.body.style.cursor = "crosshair"

    // The reporter's own dialog and, critically, its BACKDROP sit above the
    // page. elementFromPoint would return the backdrop for every position, so
    // the whole viewport read as one element. Neutralising pointer events
    // makes elementFromPoint see through them.
    const shielded = Array.from(
      document.querySelectorAll<HTMLElement>(
        '[data-slot$="-overlay"], [data-slot="dialog-content"], [data-slot="sheet-content"], [data-slot="alert-dialog-content"]',
      ),
    ).map((el) => [el, el.style.pointerEvents] as const)
    for (const [el] of shielded) el.style.pointerEvents = "none"

    let hovered: Element | null = null

    const onMove = (e: MouseEvent) => {
      const el = document.elementFromPoint(e.clientX, e.clientY)
      if (
        !el ||
        isOurs(el) ||
        el === document.body ||
        el === document.documentElement ||
        el.tagName === "NEXTJS-PORTAL"
      ) {
        overlay.style.display = "none"
        hovered = null
        return
      }
      if (el === hovered) return
      hovered = el
      const r = el.getBoundingClientRect()
      overlay.style.display = "block"
      overlay.style.top = `${r.top}px`
      overlay.style.left = `${r.left}px`
      overlay.style.width = `${r.width}px`
      overlay.style.height = `${r.height}px`
    }

    const onClick = (e: MouseEvent) => {
      const el = document.elementFromPoint(e.clientX, e.clientY)
      if (!el || isOurs(el)) return
      e.preventDefault()
      e.stopPropagation()
      teardown()
      resolve({ element: el, anchor: captureAnchor(el) })
    }

    const onKey = (e: KeyboardEvent) => {
      if (e.key !== "Escape") return
      e.preventDefault()
      e.stopPropagation()
      teardown()
      resolve(null)
    }

    function teardown() {
      overlay.remove()
      hint.remove()
      for (const [el, previous] of shielded) el.style.pointerEvents = previous
      document.body.style.cursor = previousCursor
      document.removeEventListener("mousemove", onMove, true)
      document.removeEventListener("click", onClick, true)
      document.removeEventListener("keydown", onKey, true)
    }

    document.addEventListener("mousemove", onMove, true)
    document.addEventListener("click", onClick, true)
    document.addEventListener("keydown", onKey, true)
  })
}
