// GENERATED by fadymondy.com-v2/packages/sync-feedback.mjs from packages/feedback-sdk/core/transport.ts — do not edit here, edit packages/feedback-sdk.

/**
 * The wire contract: exactly the capture columns of fadymondy.com's `reports`
 * resource (togo.resources.yaml), so every product's reports can land in the
 * same tracker with no schema change. `meta` is free-form product context
 * (build id, product key, team…); a backend without a `meta` column ignores it.
 */
export type FeedbackPayload = {
  title: string
  body?: string
  issue_type: string
  page_url?: string
  route?: string
  selector?: string
  /** A data URL. Sent as a multipart file by the endpoint transport. */
  screenshot?: string
  console_log?: string
  network_log?: string
  user_agent?: string
  viewport?: string
  meta?: Record<string, unknown>
}

/** A host-supplied submitter, for backends whose API is not the plain multipart endpoint. */
export type SubmitFn<R = unknown> = (payload: FeedbackPayload) => Promise<R>

export type SubmitOptions = {
  /** Extra request headers — a product key, a CSRF token. */
  headers?: Record<string, string>
  /** Default "include", so a same-origin session cookie travels with the report. */
  credentials?: RequestCredentials
}

export function dataUrlToBlob(dataUrl: string): Blob {
  const [head, data = ""] = dataUrl.split(",", 2)
  const mime = /data:([^;]+)/.exec(head)?.[1] ?? "application/octet-stream"
  if (!head.includes(";base64")) return new Blob([decodeURIComponent(data)], { type: mime })
  const bin = atob(data)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return new Blob([bytes], { type: mime })
}

/**
 * Send a report. A function is called as-is; an endpoint gets
 * `POST multipart/form-data` with one field per payload key, `screenshot` as a
 * PNG file and `meta` as JSON.
 */
export async function submit<R = unknown>(
  target: string | SubmitFn<R>,
  payload: FeedbackPayload,
  options: SubmitOptions = {},
): Promise<R> {
  if (typeof target === "function") return target(payload)

  const form = new FormData()
  for (const [key, value] of Object.entries(payload)) {
    if (value === undefined || value === null || value === "") continue
    if (key === "screenshot") {
      const blob = dataUrlToBlob(String(value))
      form.append(key, blob, `screenshot.${blob.type.split("/")[1] || "png"}`)
    } else if (key === "meta") {
      form.append(key, JSON.stringify(value))
    } else {
      form.append(key, String(value))
    }
  }

  const res = await fetch(target, {
    method: "POST",
    body: form,
    headers: options.headers,
    credentials: options.credentials ?? "include",
  })
  if (!res.ok) throw new Error(`The report was not accepted (${res.status})`)
  const type = res.headers.get("content-type") ?? ""
  return (type.includes("json") ? await res.json() : await res.text()) as R
}
