#!/usr/bin/env node
/*
Build the note engine WebView pages (MH-368): `npm run build:editor`.

  editor-web/editor-main.mts -> src/features/editor/editor-html.gen.ts  (EDITOR_HTML)
  editor-web/export-main.mts -> src/features/editor/export-html.gen.ts  (EXPORT_HTML)

Each output is ONE self-contained HTML document (JS + CSS + the Lusail
face inlined) exported as a string constant, so the app loads it with
<WebView source={{ html }}> and nothing is fetched at runtime but note images.

The pages bundle the web console's own modules (TipTap schema, markdown
renderer, themes, exporters) straight from ../web, so the phone and the web
render notes identically. Bare imports resolve from mobile/node_modules only
(the web package's node_modules is not needed, and pinning one tree keeps the
output deterministic across machines).

The output is deterministic — no timestamps — so an unchanged source produces
an unchanged file and a clean diff. Flags:
  --check   also type-check editor-web with its own tsconfig
  --meta    print the largest inputs per bundle
*/
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const here = path.dirname(fileURLToPath(import.meta.url));
const mobile = path.resolve(here, "..");
const web = path.resolve(mobile, "..", "web");
const modules = path.join(mobile, "node_modules");
const outDir = path.join(mobile, "src", "features", "editor");
const args = new Set(process.argv.slice(2));

/** `@/x` -> web/x (the web console's own alias), for any web module that uses it. */
const webAlias = {
  name: "web-alias",
  setup(b) {
    b.onResolve({ filter: /^@\// }, (a) => b.resolve(`./${a.path.slice(2)}`, { resolveDir: web, kind: a.kind }));
    b.onResolve({ filter: /^@shared\// }, (a) => b.resolve(`./lib/${a.path.slice(8)}`, { resolveDir: web, kind: a.kind }));
  },
};

/** web's docx exporter asks for a Node buffer; give it the base64 shim. */
const docxShim = {
  name: "docx-shim",
  setup(b) {
    const exporter = path.join(web, "lib", "notes", "export", "docx.ts");
    b.onResolve({ filter: /^docx$/ }, (a) =>
      path.resolve(a.importer) === exporter ? { path: path.join(mobile, "editor-web", "docx-shim.mts") } : undefined,
    );
  },
};

async function bundle(entry) {
  const result = await build({
    entryPoints: [path.join(mobile, "editor-web", entry)],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    // WKWebView on iOS 15+, Android System WebView (Chromium) 100+.
    target: ["safari15", "chrome100"],
    minify: true,
    legalComments: "none",
    charset: "utf8",
    nodePaths: [modules],
    plugins: [webAlias, docxShim],
    define: { "process.env.NODE_ENV": '"production"', global: "globalThis" },
    metafile: true,
    logLevel: "warning",
  });
  if (args.has("--meta")) {
    const inputs = Object.entries(result.metafile.outputs)[0][1].inputs;
    const top = Object.entries(inputs)
      .map(([file, v]) => [file.replace(/^.*node_modules\//, ""), v.bytesInOutput])
      .sort((a, b) => b[1] - a[1])
      .slice(0, 15);
    console.log(`\n${entry} — largest inputs`);
    for (const [file, bytes] of top) console.log(`  ${(bytes / 1024).toFixed(1).padStart(8)} KB  ${file}`);
  }
  return result.outputFiles[0].text;
}

/** Lusail (the app's Arabic+Latin face) so "System" matches the native UI. */
function fontFaces() {
  const face = (file, weight) => {
    const data = readFileSync(path.join(mobile, "assets", "fonts", file)).toString("base64");
    return `@font-face{font-family:Lusail;font-weight:${weight};font-style:normal;font-display:swap;src:url(data:font/ttf;base64,${data}) format("truetype")}`;
  };
  return face("Lusail-Regular.ttf", "100 450") + face("Lusail-Medium.ttf", "451 900");
}

function page(js, fonts) {
  // An inline script ends at the first "</script" whatever the JS means by it.
  const safeJs = js.replace(/<\/script/gi, "<\\/script");
  return [
    "<!doctype html>",
    '<html dir="auto"><head><meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">',
    "<meta name=\"color-scheme\" content=\"light dark\">",
    `<style>${fonts}html,body{margin:0;background:transparent}</style>`,
    '</head><body><main id="zk-root"></main>',
    `<script>${safeJs}</script>`,
    "</body></html>",
  ].join("");
}

function writeGen(file, name, html, entry) {
  const body = [
    "// generated by scripts/build-editor.mjs — do not edit",
    `// source: editor-web/${entry} (npm run build:editor)`,
    "/* eslint-disable */",
    `export const ${name}: string = ${JSON.stringify(html)};`,
    "",
  ].join("\n");
  writeFileSync(path.join(outDir, file), body);
  return Buffer.byteLength(body);
}

const fonts = fontFaces();
const targets = [
  ["editor-main.mts", "editor-html.gen.ts", "EDITOR_HTML"],
  ["export-main.mts", "export-html.gen.ts", "EXPORT_HTML"],
];

for (const [entry, file, name] of targets) {
  const js = await bundle(entry);
  const bytes = writeGen(file, name, page(js, fonts), entry);
  console.log(`${file.padEnd(22)} ${(bytes / 1024).toFixed(0).padStart(6)} KB  (js ${(js.length / 1024).toFixed(0)} KB)`);
}

if (args.has("--check")) {
  const tsc = spawnSync(path.join(modules, ".bin", "tsc"), ["-p", path.join(mobile, "editor-web", "tsconfig.json")], { stdio: "inherit" });
  if (tsc.status !== 0) process.exit(tsc.status ?? 1);
  console.log("editor-web type-check ok");
}
