// GENERATED by fadymondy.com-v2/packages/sync-grid.mjs from web/lib/brand/marks.ts — do not edit here.

// Cube-lattice mark system. Every mark is a set of cubes on a square grid
// where a cube may only sit on a cell where (col + row) is odd — this is why
// cubes touch only at corners, never along an edge. Source of truth:
// design_handoff_fady_mondy_brand/README.md.

export type Cell = readonly [col: number, row: number];

export interface MarkSpec {
  name: string;
  cells: readonly Cell[];
  /** Cells rendered in the accent colour instead of the body colour. */
  accentCells: readonly Cell[];
  body: string;
  accent: string;
  /** Body colour to use when rendered on a dark ground, if different. */
  bodyOnDark?: string;
  /**
   * The site's dark-mode ACTION colour, when bodyOnDark is not one (an ivory mark would paint
   * every dark-mode button ivory). Only the site theme reads this; the mark never does.
   */
  actionOnDark?: string;
}

export const FADY_MONDY_MARK: MarkSpec = {
  name: "Fady Mondy",
  cells: [
    [1, 0],
    [3, 0],
    [0, 1],
    [2, 1],
    [1, 2],
    [3, 2],
    [0, 3],
    [2, 3],
  ],
  accentCells: [[3, 0]],
  body: "#0E1A3C",
  bodyOnDark: "#F0EBE1",
  accent: "#C9A227",
};

export const PRODUCT_MARKS: Record<string, MarkSpec> = {
  tomatophp: {
    name: "TomatoPHP",
    cells: [
      [3, 0],
      [2, 1],
      [4, 1],
      [3, 2],
      [5, 2],
      [2, 3],
      [4, 3],
      [3, 4],
    ],
    accentCells: [[3, 0]],
    body: "#D64524",
    accent: "#4E9A3E",
  },
  togo: {
    name: "ToGO",
    cells: [
      [0, 1],
      [1, 0],
      [1, 2],
      [2, 1],
      [2, 3],
      [3, 2],
    ],
    accentCells: [
      [2, 1],
      [2, 3],
      [3, 2],
    ],
    body: "#0E1A3C",
    bodyOnDark: "#F0EBE1",
    accent: "#1F8A99",
  },
  laravilt: {
    name: "Laravilt",
    cells: [
      [0, 1],
      [1, 2],
      [0, 3],
      [2, 1],
      [2, 3],
      [3, 2],
      [4, 1],
    ],
    accentCells: [
      [2, 1],
      [2, 3],
      [3, 2],
      [4, 1],
    ],
    body: "#FF2D20",
    accent: "#9553E9",
  },
  "3x1": {
    name: "3x1.io",
    cells: [
      [3, 0],
      [2, 1],
      [4, 1],
      [3, 2],
      [2, 3],
      [4, 3],
      [3, 4],
    ],
    accentCells: [[3, 0]],
    body: "#1FCF4D",
    accent: "#0E7A33",
  },
  "mark-it-down": {
    name: "Mark It Down",
    cells: [
      [1, 0],
      [3, 0],
      [5, 0],
      [2, 1],
      [4, 1],
      [3, 2],
    ],
    accentCells: [[3, 0]],
    body: "#3D5A8C",
    // The 2026 product-marks sheet draws this mark ivory on the indigo ground. The lifted blue
    // stays as the dark-mode ACTION colour, so an ivory mark does not turn the buttons ivory.
    bodyOnDark: "#F0EBE1",
    actionOnDark: "#7E93C4",
    accent: "#C9A227",
  },
  "health-debug": {
    name: "Health Debug",
    cells: [
      [1, 0],
      [3, 0],
      [0, 1],
      [2, 1],
      [4, 1],
      [1, 2],
      [3, 2],
      [2, 3],
    ],
    accentCells: [[3, 0]],
    body: "#B0243F",
    // The marks sheet keeps the same red on the dark ground. A button needs more contrast than a
    // mark does, so the lifted red remains the dark-mode action colour.
    actionOnDark: "#D9455F",
    accent: "#C9A227",
  },
  circlexo: {
    name: "CircleXO",
    cells: [
      [3, 0],
      [2, 1],
      [4, 1],
      [1, 2],
      [5, 2],
      [2, 3],
      [4, 3],
      [3, 4],
    ],
    accentCells: [[3, 0]],
    body: "#6FA8D6",
    accent: "#C9A227",
  },
  // CaBrain — "the vault": a dome of six cubes over a solid nucleus, standing on two. The only
  // mark in the family whose centre is filled. From CaBrain Brand.dc.html, shifted one column
  // so every cell has odd (col + row); rendering normalises to the bounding box.
  cabrain: {
    name: "CaBrain",
    cells: [
      [3, 0],
      [2, 1],
      [4, 1],
      [1, 2],
      [3, 2],
      [5, 2],
      [2, 3],
      [4, 3],
    ],
    accentCells: [[3, 0]],
    // The 2026 product-marks sheet keeps the violet on the indigo ground too.
    body: "#6D4DE6",
    accent: "#C9A227",
  },
  // Booki — a month grid with one booked day: three calendar rows, the gold cube is the booking.
  // From the 2026 product-marks sheet, shifted one column so every cell has odd (col + row);
  // rendering normalises to the bounding box.
  booki: {
    name: "Booki",
    cells: [
      [1, 0],
      [3, 0],
      [5, 0],
      [2, 1],
      [4, 1],
      [1, 2],
      [3, 2],
      [5, 2],
    ],
    accentCells: [[4, 1]],
    body: "#B8479B",
    accent: "#C9A227",
  },
  // Flow Master — from the 2026 product-marks sheet, as drawn (already odd-sum).
  "flow-master": {
    name: "Flow Master",
    cells: [
      [3, 0],
      [0, 1],
      [2, 1],
      [4, 1],
      [1, 2],
      [3, 2],
      [2, 3],
      [4, 3],
    ],
    accentCells: [[3, 0]],
    body: "#2FA37A",
    accent: "#C9A227",
  },
  // Claude Agents Team — a leader with two branches beneath it: a team.
  "claude-agents-team": {
    name: "Claude Agents Team",
    cells: [
      [3, 0],
      [2, 1],
      [4, 1],
      [1, 2],
      [5, 2],
    ],
    accentCells: [[3, 0]],
    body: "#3B5BDB",
    accent: "#C9A227",
  },
  // Claude Digital Twin — two opposed arcs meeting at the base: a twin.
  "claude-digital-twin": {
    name: "Claude Digital Twin",
    cells: [
      [1, 0],
      [3, 0],
      [0, 1],
      [4, 1],
      [1, 2],
      [3, 2],
      [2, 3],
    ],
    accentCells: [[3, 0]],
    body: "#00A0A8",
    accent: "#C9A227",
  },
  // Claude Github PMS — a bar running on with a marker raised above it: a timeline.
  "claude-github-pms": {
    name: "Claude Github PMS",
    cells: [
      [3, 0],
      [0, 1],
      [2, 1],
      [4, 1],
      [6, 1],
      [1, 2],
      [3, 2],
      [5, 2],
    ],
    accentCells: [[3, 0]],
    body: "#8A9A2B",
    accent: "#C9A227",
  },
  // Claude Notifications — a two-row panel with a dot at its corner: an alert.
  "claude-notifications": {
    name: "Claude Notifications",
    cells: [
      [5, 0],
      [2, 1],
      [4, 1],
      [6, 1],
      [1, 2],
      [3, 2],
      [5, 2],
    ],
    accentCells: [[5, 0]],
    body: "#C9366F",
    accent: "#C9A227",
  },
  // Managy (drawn as "iManage" on the 2026 product-marks sheet) — four cubes in a zigzag row:
  // a line of a list. As drawn (already odd-sum).
  managy: {
    name: "Managy",
    cells: [
      [1, 0],
      [3, 0],
      [0, 1],
      [2, 1],
    ],
    accentCells: [[3, 0]],
    body: "#8C3FB5",
    accent: "#C9A227",
  },
  // Cloudy — three stacked layers: a database. From the 2026 product-marks sheet, shifted one
  // column so every cell has odd (col + row); rendering normalises to the bounding box.
  cloudy: {
    name: "Cloudy",
    cells: [
      [1, 0],
      [3, 0],
      [2, 1],
      [1, 2],
      [3, 2],
      [2, 3],
      [1, 4],
      [3, 4],
    ],
    accentCells: [[3, 0]],
    body: "#2E6F9E",
    accent: "#C9A227",
  },
  "orchestra-mcp": {
    name: "Orchestra MCP",
    cells: [
      [3, 2],
      [4, 3],
      [5, 2],
      [6, 1],
    ],
    accentCells: [[6, 1]],
    body: "#D97757",
    accent: "#8C3B1F",
  },
};
